language: node_js

node_js:
  - "node"

before_install:
  - cp ./server/config.example.js ./server/config.js
  - cp ./client/config.example.js ./client/config.js

script:
  - yarn run lint:nofix
  - yarn test
  - yarn build